spring.application.name=simplypay

# Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/TESTDB
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Spring Boot 3 usually detects this, but setting it explicitly helps:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Logger
# Logging Level (Set to DEBUG to see the bodies, INFO for just summaries)
logging.level.com.welly.simplypay=DEBUG

# File Configuration
logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=100MB
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

external.api.key=